-- Deploy snowflake_stg:tables/department to snowflake

USE WAREHOUSE &warehouse;

-- XXX Add DDLs here.
CREATE OR REPLACE TABLE PRE_LANDING.DEPARTMENT
(
  DEPARTMENT_ID INTEGER,
  DEPARTMENT_NAME VARCHAR(100),
  PROFESSOR_NAME VARCHAR(200)
);
